package dev.femrek.reactadmindataprovider.config;

import org.springdoc.core.customizers.OpenApiCustomizer;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.context.annotation.Bean;

import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * Configuration class that customizes the OpenAPI documentation generated by springdoc-openapi.
 *
 * <p>This configuration specifically addresses the issue of duplicate "RA Controller" tags appearing
 * in the API documentation when controllers extend the base RAController class.
 *
 * <p>The tag cleanup logic operates as follows:
 * <ol>
 *   <li>Iterate through all operations in the OpenAPI specification</li>
 *   <li>For operations with both the "RA Controller" tag and other specific tags, remove the generic
 *       "RA Controller" tag to avoid duplication</li>
 *   <li>For operations with only the "RA Controller" tag, keep it and mark that the global tag
 *       definition should be retained</li>
 *   <li>After processing all operations, if the generic tag was never used alone, remove the
 *       global tag definition to clean up the documentation</li>
 * </ol>
 *
 * <p>This ensures that "RA Controller" appears only once in the API documentation and is only
 * present where it is truly needed.
 *
 * @see org.springdoc.core.customizers.OpenApiCustomizer
 */
@AutoConfiguration
public class RAOpenApiConfig {
    private static final String GENERIC_TAG = "RA Controller";

    @Bean
    public OpenApiCustomizer removeDuplicateGenericTag() {
        return openApi -> {
            AtomicBoolean isGenericTagUsedAlone = new AtomicBoolean(false);

            // Clean operations AND check if generic tag is needed
            openApi.getPaths().values().stream()
                    .flatMap(pathItem -> pathItem.readOperations().stream())
                    .forEach(operation -> {
                        List<String> tags = operation.getTags();

                        if (tags != null && tags.contains(GENERIC_TAG)) {
                            if (tags.size() > 1) {
                                // CASE 1: Generic tag + Specific tag exist.
                                // Remove generic tag. It is NOT "used alone" here.
                                tags.remove(GENERIC_TAG);
                            } else {
                                // CASE 2: Only Generic tag exists.
                                // We must keep it, and we mark that the global definition is still needed.
                                isGenericTagUsedAlone.set(true);
                            }
                        }
                    });

            // Final Step: If we never found the generic tag "standing alone", remove the global definition
            if (!isGenericTagUsedAlone.get() && openApi.getTags() != null) {
                openApi.getTags().removeIf(tag -> GENERIC_TAG.equals(tag.getName()));
            }
        };
    }
}